version: "3.7"
services:
  node:
    profiles:
      - dev
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: node-dev
      args:
        USER_ID: ${USER_ID-1000}
        GROUP_ID: ${GROUP_ID-1000}
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - .:/var/www/app
